### ISSUE TITLE
Version of Fantomas 2.8.1 used by this has a regression where formatting only by AST (no source) fails

### ISSUE THREAD

**Issue by 7sharp9** [ctaggart/FsAst#11]
Im wondering is the dependency on Fantomas is needed as the usage of Fantomas is a paper thin wrapper really.

**Comment by ctaggart** [comment]
Probably not. Accepting PRs to remove it

**Comment by 7sharp9** [comment]
Yeah I know you didn't really want to maintain this and I resurrected it, I dont mind removing it and cleaning some other stuff when I get a bit of time :-)

**Comment by ctaggart** [comment]
@7sharp9 https://www.nuget.org/packages/FsAst/0.1.1
