### ISSUE TITLE
Question about versions of FCS/Fantomas

### ISSUE THREAD

**Issue by maxild** [ctaggart/FsAst#16]
Hi,

I'm playing around with some ideas about building F# source code by composing the types that define the abstract syntax in the compiler.

Right now I am just using FSX scripting to get a feel for how difficult this is to get working. 

It seems that `FSharp.Compiler.Services` in version 27.0.1 changed the root namespace from `Microsoft.FSharp` to `FSharp` removing the `Microsoft.` prefix.

I would like to run with the latest version of FCS and Fantomas. There are a few problems

* FsAst uses the old namespace,
* Fantomas 3.3.0 has FSharp.Core >= 4.7.0 in nuspec

I could stay on Fantomas 2.x with the following `paket.dependencies` file

```
generate_load_scripts: true
source https://api.nuget.org/v3/index.json

storage: none
framework: netstandard2.0

nuget FSharp.Core 4.7.0
//nuget FSharp.Compiler.Service 27.0.1 <-- Namespace changed here!!!
nuget FSharp.Compiler.Service 26.0.1 // <-- The last version before the BIG breaking change!!!
nuget Fantomas 2.9.0 // The version used by FsAst
nuget FsAst
```

This works. But I have to use the old API (no async, source string,...). I am not saying this is important right now, but being on latest/greatest is not bad either.

What are your thoughts about upgrading the dependencies. I suspect the `FSharp.Core` dependency constraint of Fantomas 3.3.0 is not your cup of tea?

I have forked so that I can change the versions, but would just like to chat about this subject before hand. And my top priority is getting a feel for how cumbersome this idea is. But if we can sketch out how to to use Fantomas 3.x (that seems to be under active development) I can assist with a PR. 

P.S.

And to @7sharp9. Watched you on youtube about Myriad, and read your blog post about meta programming in F#. Great read! It reminds me a bit about the `deriving` mechanism in Haskell (Eq, Ord, Show) for some of the simpler boilerplate classes. 

In my case I am thinking about using codegen for lookup (code) SQL tables similar to what SqlEnumProvider is for. I just have 100+ lookup tables, and I need to weave those "magic string/symbols" types into my domain model. So I would like to avoid the TP approach. Not sure this is a job for Myriad, but the need for some DSL (helpers) to compose ast types is definitely needed. I am not sure if I could use quotations for this, but I am interested in parser techniques and language, so out of interest, I will accept the pain using types from `ast.fs`. And the codegen is simple, because I will generate the same shape over and over again, kind of like only needing a single plugin in Myriad. 

Also just writing the codegen using string manipulations would get the job done. But like I said, I am fairly new to F#, and need some hard core problems to learn the hard way:smile:

**Comment by ctaggart** [comment]
Fixed by #17. 0.2.0 has been published. https://github.com/ctaggart/FsAst/releases/tag/0.2.0
