### ISSUE TITLE
Remove the formatting of AST, it creates a dependency on Fantomas that's not really needed for what's really a one liner

### ISSUE THREAD

**Issue by 7sharp9** [ctaggart/FsAst#27]
I removed the usage of the format method earlier in Myriad as it was causing issues with a mismatched Fantomas dependency.  It's also probably a good idea to just keep this lib for helping create art elements and keep Fantomas doing the formatting.  I can PR the removal if it's agreeable.

**Comment by Krzysztof-Cieslak** [comment]
Done in c0517bebf26732ae9954b3f410c9d59e2bfe4668
