### ISSUE TITLE
Update to FSC 39

### ISSUE THREAD

**Issue by xperiandri** [ctaggart/FsAst#33]
**Is your feature request related to a problem? Please describe.**
Snowflaqe uses FsAst and Fantomas.
Fantomas 4.5 uses FSC 39 which has breaking changes.
FsAst uses FSC 38
This means that I cannot use Fantomas 4.5

**Describe the solution you'd like**
Update to FSC 39

**Comment by baronfel** [comment]
I'll do you one better: there's an FCS 40 now as well! So ideally there would be interim versions of this library published, one for 39 and one for 40, just to cover everyone's bases.

**Comment by xperiandri** [comment]
How long could it take?

**Comment by xperiandri** [comment]
Thank you very much!

**Comment by baronfel** [comment]
We've still got to release the thing, but I'm working on an automated pipeline for that [here](https://github.com/ionide/FsAst/pull/35)
